export const technologies = [
  { name: "HTML 5", icon: "/assets/Tech/html.png" },
  { name: "CSS 3", icon: "/assets/Tech/css.png" },
  { name: "JavaScript", icon: "/assets/Tech/javascript.png" },
  { name: "Postman", icon: "/assets/Tech/postman.png" },
  { name: "GitHub", icon: "/assets/Tech/github.png" },
  { name: "React JS", icon: "/assets/Tech/reactjs.png" },
  { name: "Next JS", icon: "/assets/Tech/nextjs.png" },
  { name: "Tailwind CSS", icon: "/assets/Tech/tailwind.png" },
  { name: "Node JS", icon: "/assets/Tech/nodejs.png" },
  { name: "MongoDB", icon: "/assets/Tech/mongodb.png" },
  { name: "Three JS", icon: "/assets/Tech/threejs.svg" },
  { name: "Git", icon: "/assets/Tech/git.png" },
  { name: "MySql", icon: "/assets/Tech/mysql.png" },
];
